In [1]:
# 1
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape:", arr.shape)  # (2, 3)
print("Dimensions:", arr.ndim)  # 2
print("Size:", arr.size)  # 6
print("Data type:", arr.dtype)  # int64 (или float64 в зависимости от платформы)
print("Item size:", arr.itemsize)  # 8 (для int64)


Shape: (2, 3)
Dimensions: 2
Size: 6
Data type: int32
Item size: 4


In [2]:
# 2
array_from_list = np.array([1, 2, 3])
arange_array = np.arange(0, 10, 2)
zeros_array = np.zeros((2, 3))
ones_array = np.ones((3, 4))
identity_matrix = np.eye(3)
empty_array = np.empty((2, 2))
diag_matrix = np.diag([1, 2, 3])
random_arr = np.random.rand(2, 2)
randint_arr = np.random.randint(0, 10, size=(3, 3))

print(array_from_list)
print(arange_array)
print(zeros_array)
print(ones_array)
print(identity_matrix)
print(empty_array)
print(diag_matrix)
print(random_arr)
print(randint_arr)


[1 2 3]
[0 2 4 6 8]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[5.36369536e-080 8.82893714e+199]
 [1.99432122e+209 2.53970787e+151]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[0.78027366 0.01627421]
 [0.83369947 0.45671392]]
[[0 8 7]
 [3 9 8]
 [7 3 5]]


In [3]:
# 3
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Индексация
element = arr[1, 2]  # 6

# Сечения
sub_array = arr[0, 1:3]  # [2, 3]

# Маски
mask = arr > 3
filtered_array = arr[mask]  # [4, 5, 6]

print("Element:", element)
print("Sub-array:", sub_array)
print("Filtered array:", filtered_array)


Element: 6
Sub-array: [2 3]
Filtered array: [4 5 6]


In [4]:
#4
arr = np.array([1, 2, 3, 4, 5])
view_arr = arr[1:4]  # представление
view_arr[0] = 10  # изменяем значение в представлении

print(arr)      # [ 1 10  3  4  5]
print(view_arr) # [10  3  4]

# ----

copy_arr = arr.copy()
copy_arr[0] = 100

print(arr)      # [ 1 10  3  4  5]
print(copy_arr) # [100 10  3  4  5]


[ 1 10  3  4  5]
[10  3  4]
[ 1 10  3  4  5]
[100  10   3   4   5]


In [6]:
# 5
# Создаем массивы
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Арифметические операции
sum_array = arr1 + arr2  # Сумма массивов
prod_array = arr1 * arr2  # Произведение массивов

# Сравнение массивов
comparison = arr1 > 2  # Сравнение с 2

# Математические функции
total = np.sum(arr1)  # Сумма элементов
mean = np.mean(arr1)  # Среднее значение
std_dev = np.std(arr1)  # Стандартное отклонение

# Транслирование (broadcasting)
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])  # Одномерный массив
result = a + b  # Сложение с трансляцией

# Вывод результатов
print("arr1:", arr1)
print("arr2:", arr2)
print("Сумма массивов (sum_array):", sum_array)
print("Произведение массивов (prod_array):", prod_array)
print("Сравнение (arr1 > 2):", comparison)
print("Сумма элементов arr1:", total)
print("Среднее значение arr1:", mean)
print("Стандартное отклонение arr1:", std_dev)
print("Результат трансляции (a + b):")
print(result)


arr1: [1 2 3]
arr2: [4 5 6]
Сумма массивов (sum_array): [5 7 9]
Произведение массивов (prod_array): [ 4 10 18]
Сравнение (arr1 > 2): [False False  True]
Сумма элементов arr1: 6
Среднее значение arr1: 2.0
Стандартное отклонение arr1: 0.816496580927726
Результат трансляции (a + b):
[[11 22 33]
 [14 25 36]]


# 1
ndarray (n-dimensional array) — основной класс библиотеки NumPy, который представляет многомерные массивы. Вот его основные свойства и атрибуты:

- ndarray.shape: возвращает кортеж, представляющий размеры массива по каждому измерению.
- ndarray.ndim: количество измерений (ранг массива).
- ndarray.size: общее количество элементов в массиве.
- ndarray.dtype: тип данных элементов в массиве (например, int, float и т.д.).
- ndarray.itemsize: размер в байтах одного элемента массива.
- ndarray.data: буфер, содержащий данные массива.


# 2
NumPy предоставляет множество функций для создания массивов. Вот основные из них:

- np.array(): создает массив из объекта Python (например, списка).
- np.arange(start, stop, step): создает массив с равномерно распределенными значениями в указанном диапазоне.
- np.zeros(shape): создает массив указанной формы, заполненный нулями.
- np.ones(shape): создает массив указанной формы, заполненный единицами.
- np.eye(n): создает единичную матрицу размером n x n.
- np.empty(shape): создает массив указанной формы без инициализации значений (содержимое не определено).
- np.diag(v, k=0): создает диагональную матрицу из вектора v (если k=0, то диагональ главная).
- np.random.rand(d0, d1, ..., dn): создает массив, заполненный случайными числами из равномерного распределения на отрезке [0.0, 1.0).
- np.random.randint(low, high=None, size=None): генерирует массив случайных целых чисел в заданном диапазоне.

# 3
Индексация массивов в NumPy позволяет получать доступ к элементам массива с помощью индексов.

- Индексация: позволяет получать элементы массива по их позициям.
- Сечения (slicing): позволяет получать подмасивы. Например, arr[1:3] вернет элементы с индексами 1 и 2.
- Маски: использование булевых массивов для включения или исключения элементов при вычислениях. Пример: arr[arr > 0] вернет только положительные элементы из arr.

# 4
Представление в NumPy — это способ ссылаться на тот же объект данных, не создавая новую копию массива. Это полезно для экономии памяти и производительности. Когда вы изменяете элементы представления, исходный массив также изменяется. Это происходит, когда вы используете сечения.

# 5
NumPy предоставляет множество функций для выполнения различных операций:

- Арифметические действия: можно выполнять операции как с массивами, так и с отдельными числами (транслирование).
- Сравнение: можно сравнивать массивы с помощью операторов сравнения, результатом будет булев массив.
- Математические функции: NumPy содержит множество математических функций, таких как np.sum(), np.mean(), np.std(), которые работают на массивах.
- Транслирование (broadcasting): позволяет выполнять операции над массивами разной формы. NumPy автоматически «расширит» меньший массив до формы большего.
Транслирование (broadcasting) в NumPy — это механизм, позволяющий выполнять арифметические операции над массивами разной формы. Он автоматически расширяет меньший массив до формы большего, чтобы соответствовать размерностям.
Транслирование может работать для двух массивов в том случае, если их размерности совместимы: их длина равна, или длина одной из них — 1. Если эти условия не соблюдены, возникает исключение, сообщающее, что два массива не совместимы